### ISSUE TITLE
When templating I want to automatically link tickets with a search

### ISSUE THREAD

**Issue by Ghalko** [joplin/plugin-templates#60]
Extend dropdown to be able to display search results of notes to be chosen as the variable to be inserted into the new note.

Single row, generic search
```yaml
ticket: search
```

More specific:
```yaml
ticket:
  label: Ticket to link
  type: search
  notebook: "Kanban"
  -tag: "*"
```

The dropdown could be populated initially or require some text to start being typed in order to start the search. Note the search constraints mirror the search syntax.
